# Generates lib/prawn_ex/font/afm.ex: WinAnsi advance widths (1/1000 em) for
# the base-14 Helvetica and Times families, read from the Adobe AFM files
# that ship with the Prawn gem.
#
#   ruby scripts/gen_afm_metrics.rb
require "prawn"

FONTS = %w[Helvetica Helvetica-Bold Helvetica-Oblique Helvetica-BoldOblique
           Times-Roman Times-Bold Times-Italic Times-BoldItalic]
afm_dir = File.join(Gem.loaded_specs["prawn"].full_gem_path, "data/fonts")
names = Prawn::Encoding::WinAnsi::CHARACTERS

tables = FONTS.map do |font|
  widths = {}
  File.foreach(File.join(afm_dir, "#{font}.afm")) do |line|
    next unless line.start_with?("C ")
    fields = line.split(";").map(&:strip)
    wx = fields.find { |f| f.start_with?("WX ") }.split.last.to_i
    name = fields.find { |f| f.start_with?("N ") }.split.last
    widths[name] = wx
  end
  row = (32..255).map { |code| widths.fetch(names[code], widths["space"]) }
  "    \"#{font}\" =>\n      {#{row.each_slice(16).map { |s| s.join(', ') }.join(",\n       ")}}"
end

File.write("lib/prawn_ex/font/afm.ex", <<~ELIXIR)
  # Generated by scripts/gen_afm_metrics.rb from the Adobe core-14 AFM files.
  # Do not edit by hand.
  defmodule PrawnEx.Font.AFM do
    @moduledoc """
    Advance widths for the built-in (base-14) fonts, so text can be measured
    exactly instead of estimated.

    Widths are in 1/1000 em for WinAnsi codes 32..255, the encoding every
    built-in font is written with.
    """

    @widths %{
  #{tables.join(",\n")}
    }

    @doc "Names of the built-in fonts with known metrics."
    @spec fonts() :: [String.t()]
    def fonts, do: Map.keys(@widths)

    @doc "Returns the width table for `font`, or `nil` if it is unknown."
    @spec widths(String.t()) :: tuple() | nil
    def widths(font), do: Map.get(@widths, font)
  end
ELIXIR
